# Generated by Django 5.2.15 on 2026-09-04 10:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                ("full_name", models.CharField(max_length=120)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Format: 263775000000 (no +, no leading 0)",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="drivers/photos/"
                    ),
                ),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("hiace", "Hiace"),
                            ("corolla", "Corolla"),
                            ("wish", "Wish"),
                            ("other", "Other"),
                        ],
                        default="hiace",
                        max_length=20,
                    ),
                ),
                ("car_reg", models.CharField(max_length=20)),
                ("seats", models.PositiveSmallIntegerField(default=4)),
                ("base_area", models.CharField(default="Mvurwi Town", max_length=120)),
                ("base_lat", models.FloatField(blank=True, null=True)),
                ("base_lng", models.FloatField(blank=True, null=True)),
                (
                    "routes",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, e.g. Harare, Bindura, NOC",
                        max_length=255,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active_listing", models.BooleanField(default=True)),
                ("pro_until", models.DateTimeField(blank=True, null=True)),
                ("last_online_at", models.DateTimeField(blank=True, null=True)),
                ("leads_used_this_month", models.PositiveIntegerField(default=0)),
                (
                    "leads_reset_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("going_to_used_this_month", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_verified", "-pro_until", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="Fare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(default="Mvurwi", max_length=80)),
                ("destination", models.CharField(max_length=80)),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=6)),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "destination"],
                "unique_together": {("origin", "destination")},
            },
        ),
        migrations.CreateModel(
            name="GoingToPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=120)),
                ("seats_available", models.PositiveSmallIntegerField()),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "departure_text",
                    models.CharField(
                        help_text="Free text, e.g. '2pm today'", max_length=80
                    ),
                ),
                ("is_pinned_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="going_to_posts",
                        to="taxis.driver",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("passive", "Passive"), ("hot", "Hot")],
                        default="hot",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("unlocked", "Unlocked"),
                            ("expired", "Expired"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("passenger_name", models.CharField(max_length=80)),
                ("passenger_phone", models.CharField(max_length=20)),
                ("pickup", models.CharField(max_length=120)),
                ("destination", models.CharField(max_length=120)),
                ("people", models.PositiveSmallIntegerField(default=1)),
                (
                    "requested_time",
                    models.CharField(
                        blank=True,
                        help_text="Free text, e.g. 'Now', '2pm'",
                        max_length=80,
                    ),
                ),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver_profile_viewed",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only for passive leads originating from a specific driver profile.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passive_leads_seen",
                        to="taxis.driver",
                    ),
                ),
                (
                    "unlocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hot_leads_won",
                        to="taxis.driver",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("hot_lead", "Hot Lead Unlock"),
                            ("pro_weekly", "Pro Subscription (Weekly)"),
                            ("pro_monthly", "Pro Subscription (Monthly)"),
                            ("going_to_pin", "Going-To Pin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("ecocash", "EcoCash (manual)"), ("paynow", "Paynow")],
                        default="ecocash",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("amount_usd", models.DecimalField(decimal_places=2, max_digits=6)),
                ("ecocash_reference", models.CharField(blank=True, max_length=40)),
                (
                    "proof_of_payment",
                    models.ImageField(
                        blank=True, null=True, upload_to="payments/proof/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="taxis.driver",
                    ),
                ),
                (
                    "related_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="taxis.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passenger_name",
                    models.CharField(blank=True, default="Anonymous", max_length=80),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="taxis.driver",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
