# Generated by Django 5.2.15 on 2026-09-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("passenger", "Passenger"),
                            ("driver", "Driver"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "question"],
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Optional, but needed if you ever want to reset your password by email.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(
                help_text="Your phone number, used to log in (e.g. 0775123456). This is stored as your username — passengers never see it directly; they reach you through the WhatsApp button.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="A clear photo of your car. Listings with a photo get more clicks.",
                null=True,
                upload_to="drivers/photos/",
            ),
        ),
    ]
